version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 80:80
    networks:
      - frontend

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 3333:5000
    env_file:
      - ./backend/.env.production
    depends_on:
      - mongodb
    networks:
      - frontend
      - backend

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    networks:
      - backend

volumes:
  mongodb_data:
    external: false

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge