version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile-dev
    ports:
      - "80:5173"

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
    external: false