version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 8088:80
    networks:
      - frontend
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 5000:5000
      - 7002:7002
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - ./backend/.env.production
    depends_on:
      - mongodb
    networks:
      - frontend
      - backend

  mongodb:
    image: mongo:3.2
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: rootpassword
    #   MONGO_INITDB_DATABASE: machineData
    ports:
      - 27217:27017
    volumes:
      - mongodb_data:/data/db
    networks:
      - backend

  # machinesim:
  #   build:
  #     context: ./machine-sim
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - backend
  #   networks:
  #     - backend

volumes:
  mongodb_data:
    external: false

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
